name: BSC Integration Test

on:
  push:
    branches:
      - feature/bsc-integration-testing

jobs:
  compile:
    name: BSC Integration Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout bsc-docker-deploy
        uses: actions/checkout@v4
        with:
          # Repository name with owner. For example, actions/checkout
          # Default: ${{ github.repository }}
          repository: 'bnb-chain/bsc-docker-deploy'
          token: ${{ secrets.PAT }}
          path: "bsc-docker-deploy"
          ref: 'feature/dinamic-entrypoint'
      - name: Checkout bsc-genesis-contract
        uses: actions/checkout@v4
        with:
          repository: 'bnb-chain/bsc-genesis-contract'
          token: ${{ secrets.PAT }}
          path: "bsc-docker-deploy/bsc-genesis-contract"
      - name: Checkout node
        uses: actions/checkout@v4
        with:
          repository: 'bnb-chain/node'
          token: ${{ secrets.PAT }}
          path: "bsc-docker-deploy/node"
      - name: Checkout bsc
        uses: actions/checkout@v4
        with:
          repository: 'bnb-chain/bsc'
          token: ${{ secrets.PAT }}
          path: "bsc-docker-deploy/bsc"
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: bsc-docker-deploy/
          tags: bnb-chain.local/bsc-integration-testing:latest
      - name: Checkout bsc-integration-testing
        uses: actions/checkout@v4
        with:
          repository: 'bnb-chain/bsc-integration-testing'
          token: ${{ secrets.PAT }}
          path: "bsc-integration-testing"
      - name: Setup Go 1.21
        uses: actions/setup-go@v4
        with:
          go-version: "1.21"
      - name: Go test with docker containers
        uses: bnb-alexlucaci/go-test-docker-run-action@v2
        with:
          run: |
            cd bsc-integration-testing
            env VOLUME_MOUNT_PATH=${{ runner.workspace }}/bsc-integration-testing/foundation/test IMAGE_NAME=bnb-chain.local/bsc-integration-testing:latest go test -v ./...
